name: Supplements Weekly Agent

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SEARCH_API_KEY: ${{ secrets.SEARCH_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Node version
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install & run (Node)
        run: |
          npm ci
          npm run build --if-present
          node dist/agent.js || node agent.js
